version: '3.3'
services:

  # database:
  #   image: "postgres:latest"
  #   env_file:
  #     - ./env/database.env
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped


  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./env/pgadmin.env
    volumes:
      - pgadmin:/var/lib/pgadmin4
    ports:
      - "5050:80"
    restart: unless-stopped
    # depends_on:
    #   - database

  backend:
    build: ./backend/
    ports:
      - "8080:80"
    restart: unless-stopped
    # depends_on:
    #   - database

volumes:
    postgres:
    pgadmin: